application: personal-polymer-material
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /assets
  static_dir: assets  
- url: /components
  static_dir: components
- url: /elements
  static_dir: elements
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest  
